config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    collection do
      post :generate
      get :missing_body_count
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
# frozen_string_literal: true

class Person
  attr_accessor :name, :age

  def initialize(name, age)
    @name = name
    @age = age
  end

  def as_hash
    {
      name: name,
      age: age
    }
  end
end

app/models/post.rb
# frozen_string_literal: true

require 'net/http'
require 'securerandom'

class Post < ApplicationRecord
  validates :title, uniqueness: true

  scope :ordered, -> { order(body: :asc, id: :asc) }

  before_create :set_expires_at

  def self.set_scores
    Post.where(score: nil).each_with_index do |post, index|
      post.update!(score: (index + 1))
    end
  end

  def self.set_body
    Post.where(body: nil).each_with_index do |post, _index|
      post.set_body!
    end
  end

  def set_body!
    update!(body: self.class.pull_body)
  end

  def self.generate!
    body = begin
             pull_body
           rescue StandardError
             nil
           end
    Post.create!(title: "generated #{SecureRandom.uuid}", body: body)
  end

  TITLES = ['cow says moo', 'title one', 'funny title', 'this is barely random']
  def self.suggest_title
    TITLES.sample
  end

  private

  ###
  # This method is to exercise hitting external network requests
  # to not overload free providers we randomly switch between a few
  # each has some different options / results
  ###
  def self.pull_body
    # NOTE: __DO NOT SOLVE__ Flaky Specs by removing this rand
    # this rand is to help send different network errors
    # and success randomly
    if rand(7) > 1
      body_from_json_placeholder
    else
      body_from_json_beeceptor
    end
  end

  def self.body_from_json_placeholder
    url = URI.parse('http://jsonplaceholder.typicode.com/posts/1')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port, open_timeout: 3, read_timeout: 3) do |http|
      http.request(req)
    end
    JSON.parse(res.body)['title']
  end

  def self.body_from_json_beeceptor
    url = URI.parse('http://flaky-examples.free.beeceptor.com/get_text')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port, open_timeout: 3, read_timeout: 3) do |http|
      http.request(req)
    end
    JSON.parse(res.body)['title']
  end

  def set_expires_at
    self.expires_at ||= Time.current + 2.days
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = if params[:filter]
               Post.where(body: params[:filter])
             else
               Post.all
             end
  end

  def missing_body_count
    @total_count = Post.count
    @missing_count = Post.where(body: nil).count
    render layout: false
  end

  def generate
    Post.generate!
    redirect_to '/posts'
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :score)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  ###
  # This is a bad example of a helper file / methods, but it isn't uncommon to have
  # class variable based caches, initilized on boot in Rails.
  # These class vars, can lead to common testing gotchas.
  #
  # This kind of error is also common with caches / key value stories like redis
  ###
  @@bad_class_counter = 1

  def get_counter
    @@bad_class_counter
  end

  def increament_counter(val)
    @@bad_class_counter += val
  end

  PAGE_HITS_KEY = 'PAGE_HITS_KEY_v1'
  def hits_counter
    REDIS.get(PAGE_HITS_KEY) || (increament_hits && '1')
  end

  def increament_hits
    REDIS.incr(PAGE_HITS_KEY)
  end

  def generated_on
    Time.current.strftime("%b, %-d, %Y")
  end

  def generated_on_cached
    Rails.cache.fetch("generated_on_cached", expires_in: 1.day) do
      generated_on
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlakySpecExamples</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag '$.fx.off = true;' if ENV['SOLVED_SPECS'] %>
  </head>

  <body>
    <%= yield %>
    <hr/>
    <p>generated on: <%= generated_on %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: 'post-form') do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit class: 'post-submit' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
          <td><%= post.score %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% elsif params[:filter].present? %>
      <tr colspan='6'>
        <td>No posts found</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %><br/>
<%= button_to 'Generate Post', generate_posts_path, class: 'generate-submit' %><br/>

<div>
  Post Totals<br/>
  <div data-load-url="/posts/missing_body_count">loading...</div>
</div>

app/views/posts/missing_body_count.html.erb
total: <%= @total_count %>, 
missing body: <%= @missing_count %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Score:</strong>
  <%= @post.score %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>